import {
  OrderDirection,
  query,
  RepositoryOrderField,
  resolved,
} from '../src/gqty';
import assert from 'assert';
import { getFields, getArrayFields } from 'gqty';

test('works', async () => {
  expect(
    await resolved(() => {
      const user = query.user({
        login: 'PabloSzx',
      });

      assert(user, 'User Not Found');

      const repos = user.repositoriesContributedTo({
        first: 10,
        orderBy: {
          field: RepositoryOrderField.STARGAZERS,
          direction: OrderDirection.DESC,
        },
      });

      return {
        pageInfo: getFields(repos.pageInfo),
        nodes: getArrayFields(repos.nodes),
      };
    })
  ).toMatchInlineSnapshot(`
    Object {
      "nodes": Array [
        Object {
          "__typename": "Repository",
          "autoMergeAllowed": false,
          "createdAt": "2014-06-17T15:28:39Z",
          "databaseId": 20929025,
          "deleteBranchOnMerge": true,
          "description": "TypeScript is a superset of JavaScript that compiles to clean JavaScript output.",
          "descriptionHTML": "<div>TypeScript is a superset of JavaScript that compiles to clean JavaScript output.</div>",
          "diskUsage": 1526852,
          "forkCount": 9750,
          "forkingAllowed": true,
          "hasIssuesEnabled": true,
          "hasProjectsEnabled": true,
          "hasWikiEnabled": true,
          "homepageUrl": "https://www.typescriptlang.org",
          "id": "MDEwOlJlcG9zaXRvcnkyMDkyOTAyNQ==",
          "isArchived": false,
          "isBlankIssuesEnabled": false,
          "isDisabled": false,
          "isEmpty": false,
          "isFork": false,
          "isInOrganization": true,
          "isLocked": false,
          "isMirror": false,
          "isPrivate": false,
          "isSecurityPolicyEnabled": true,
          "isTemplate": false,
          "isUserConfigurationRepository": false,
          "lockReason": null,
          "mergeCommitAllowed": true,
          "mirrorUrl": null,
          "name": "TypeScript",
          "nameWithOwner": "microsoft/TypeScript",
          "openGraphImageUrl": "https://avatars.githubusercontent.com/u/6154722?s=400&v=4",
          "projectsResourcePath": "/microsoft/TypeScript/projects",
          "projectsUrl": "https://github.com/microsoft/TypeScript/projects",
          "pushedAt": "2021-09-20T22:17:56Z",
          "rebaseMergeAllowed": true,
          "resourcePath": "/microsoft/TypeScript",
          "securityPolicyUrl": "https://github.com/microsoft/TypeScript/security/policy",
          "squashMergeAllowed": true,
          "sshUrl": "git@github.com:microsoft/TypeScript.git",
          "stargazerCount": 74399,
          "tempCloneToken": "",
          "updatedAt": "2021-09-20T23:18:24Z",
          "url": "https://github.com/microsoft/TypeScript",
          "usesCustomOpenGraphImage": false,
          "viewerCanAdminister": false,
          "viewerCanCreateProjects": false,
          "viewerCanSubscribe": true,
          "viewerCanUpdateTopics": false,
          "viewerDefaultCommitEmail": "pablosaez1995@gmail.com",
          "viewerDefaultMergeMethod": "MERGE",
          "viewerHasStarred": true,
          "viewerPermission": "READ",
          "viewerPossibleCommitEmails": Array [
            "pablo.saez@hotmail.com",
            "pablo.saez01@alumnos.uach.cl",
            "pablosaez1995@gmail.com",
          ],
          "viewerSubscription": null,
          "visibility": "PUBLIC",
        },
        Object {
          "__typename": "Repository",
          "autoMergeAllowed": false,
          "createdAt": "2016-10-05T23:32:51Z",
          "databaseId": 70107786,
          "deleteBranchOnMerge": true,
          "description": "The React Framework",
          "descriptionHTML": "<div>The React Framework</div>",
          "diskUsage": 341762,
          "forkCount": 14365,
          "forkingAllowed": true,
          "hasIssuesEnabled": true,
          "hasProjectsEnabled": false,
          "hasWikiEnabled": false,
          "homepageUrl": "https://nextjs.org",
          "id": "MDEwOlJlcG9zaXRvcnk3MDEwNzc4Ng==",
          "isArchived": false,
          "isBlankIssuesEnabled": false,
          "isDisabled": false,
          "isEmpty": false,
          "isFork": false,
          "isInOrganization": true,
          "isLocked": false,
          "isMirror": false,
          "isPrivate": false,
          "isSecurityPolicyEnabled": true,
          "isTemplate": false,
          "isUserConfigurationRepository": false,
          "lockReason": null,
          "mergeCommitAllowed": false,
          "mirrorUrl": null,
          "name": "next.js",
          "nameWithOwner": "vercel/next.js",
          "openGraphImageUrl": "https://repository-images.githubusercontent.com/70107786/6532af00-82ea-11ea-9d1a-7fcded8ac5d3",
          "projectsResourcePath": "/vercel/next.js/projects",
          "projectsUrl": "https://github.com/vercel/next.js/projects",
          "pushedAt": "2021-09-20T21:28:43Z",
          "rebaseMergeAllowed": false,
          "resourcePath": "/vercel/next.js",
          "securityPolicyUrl": "https://github.com/vercel/next.js/security/policy",
          "squashMergeAllowed": true,
          "sshUrl": "git@github.com:vercel/next.js.git",
          "stargazerCount": 73402,
          "tempCloneToken": "",
          "updatedAt": "2021-09-20T22:52:01Z",
          "url": "https://github.com/vercel/next.js",
          "usesCustomOpenGraphImage": true,
          "viewerCanAdminister": false,
          "viewerCanCreateProjects": false,
          "viewerCanSubscribe": true,
          "viewerCanUpdateTopics": false,
          "viewerDefaultCommitEmail": "pablo.saez@hotmail.com",
          "viewerDefaultMergeMethod": "SQUASH",
          "viewerHasStarred": true,
          "viewerPermission": "READ",
          "viewerPossibleCommitEmails": Array [
            "pablo.saez@hotmail.com",
            "pablo.saez01@alumnos.uach.cl",
            "pablosaez1995@gmail.com",
          ],
          "viewerSubscription": null,
          "visibility": "PUBLIC",
        },
        Object {
          "__typename": "Repository",
          "autoMergeAllowed": false,
          "createdAt": "2016-09-28T19:10:14Z",
          "databaseId": 69495170,
          "deleteBranchOnMerge": true,
          "description": "Fast and low overhead web framework, for Node.js",
          "descriptionHTML": "<div>Fast and low overhead web framework, for Node.js</div>",
          "diskUsage": 5229,
          "forkCount": 1506,
          "forkingAllowed": true,
          "hasIssuesEnabled": true,
          "hasProjectsEnabled": true,
          "hasWikiEnabled": false,
          "homepageUrl": "https://www.fastify.io",
          "id": "MDEwOlJlcG9zaXRvcnk2OTQ5NTE3MA==",
          "isArchived": false,
          "isBlankIssuesEnabled": false,
          "isDisabled": false,
          "isEmpty": false,
          "isFork": false,
          "isInOrganization": true,
          "isLocked": false,
          "isMirror": false,
          "isPrivate": false,
          "isSecurityPolicyEnabled": true,
          "isTemplate": false,
          "isUserConfigurationRepository": false,
          "lockReason": null,
          "mergeCommitAllowed": false,
          "mirrorUrl": null,
          "name": "fastify",
          "nameWithOwner": "fastify/fastify",
          "openGraphImageUrl": "https://repository-images.githubusercontent.com/69495170/8125e100-61bc-11e9-8d9f-eb01f522f962",
          "projectsResourcePath": "/fastify/fastify/projects",
          "projectsUrl": "https://github.com/fastify/fastify/projects",
          "pushedAt": "2021-09-20T14:06:21Z",
          "rebaseMergeAllowed": true,
          "resourcePath": "/fastify/fastify",
          "securityPolicyUrl": "https://github.com/fastify/fastify/security/policy",
          "squashMergeAllowed": true,
          "sshUrl": "git@github.com:fastify/fastify.git",
          "stargazerCount": 20547,
          "tempCloneToken": "",
          "updatedAt": "2021-09-20T21:37:57Z",
          "url": "https://github.com/fastify/fastify",
          "usesCustomOpenGraphImage": true,
          "viewerCanAdminister": false,
          "viewerCanCreateProjects": false,
          "viewerCanSubscribe": true,
          "viewerCanUpdateTopics": false,
          "viewerDefaultCommitEmail": "pablosaez1995@gmail.com",
          "viewerDefaultMergeMethod": "SQUASH",
          "viewerHasStarred": true,
          "viewerPermission": "READ",
          "viewerPossibleCommitEmails": Array [
            "pablo.saez@hotmail.com",
            "pablo.saez01@alumnos.uach.cl",
            "pablosaez1995@gmail.com",
          ],
          "viewerSubscription": "UNSUBSCRIBED",
          "visibility": "PUBLIC",
        },
        Object {
          "__typename": "Repository",
          "autoMergeAllowed": false,
          "createdAt": "2015-06-30T12:16:50Z",
          "databaseId": 38307428,
          "deleteBranchOnMerge": false,
          "description": "A reference implementation of GraphQL for JavaScript",
          "descriptionHTML": "<div>A reference implementation of GraphQL for JavaScript</div>",
          "diskUsage": 16603,
          "forkCount": 1861,
          "forkingAllowed": true,
          "hasIssuesEnabled": true,
          "hasProjectsEnabled": true,
          "hasWikiEnabled": true,
          "homepageUrl": "http://graphql.org/graphql-js/",
          "id": "MDEwOlJlcG9zaXRvcnkzODMwNzQyOA==",
          "isArchived": false,
          "isBlankIssuesEnabled": true,
          "isDisabled": false,
          "isEmpty": false,
          "isFork": false,
          "isInOrganization": true,
          "isLocked": false,
          "isMirror": false,
          "isPrivate": false,
          "isSecurityPolicyEnabled": false,
          "isTemplate": false,
          "isUserConfigurationRepository": false,
          "lockReason": null,
          "mergeCommitAllowed": true,
          "mirrorUrl": null,
          "name": "graphql-js",
          "nameWithOwner": "graphql/graphql-js",
          "openGraphImageUrl": "https://avatars.githubusercontent.com/u/12972006?s=400&v=4",
          "projectsResourcePath": "/graphql/graphql-js/projects",
          "projectsUrl": "https://github.com/graphql/graphql-js/projects",
          "pushedAt": "2021-09-20T16:45:35Z",
          "rebaseMergeAllowed": true,
          "resourcePath": "/graphql/graphql-js",
          "securityPolicyUrl": null,
          "squashMergeAllowed": true,
          "sshUrl": "git@github.com:graphql/graphql-js.git",
          "stargazerCount": 17970,
          "tempCloneToken": "",
          "updatedAt": "2021-09-20T16:00:19Z",
          "url": "https://github.com/graphql/graphql-js",
          "usesCustomOpenGraphImage": false,
          "viewerCanAdminister": false,
          "viewerCanCreateProjects": false,
          "viewerCanSubscribe": true,
          "viewerCanUpdateTopics": false,
          "viewerDefaultCommitEmail": "pablosaez1995@gmail.com",
          "viewerDefaultMergeMethod": "MERGE",
          "viewerHasStarred": false,
          "viewerPermission": "READ",
          "viewerPossibleCommitEmails": Array [
            "pablo.saez@hotmail.com",
            "pablo.saez01@alumnos.uach.cl",
            "pablosaez1995@gmail.com",
          ],
          "viewerSubscription": "UNSUBSCRIBED",
          "visibility": "PUBLIC",
        },
        Object {
          "__typename": "Repository",
          "autoMergeAllowed": false,
          "createdAt": "2016-01-28T07:40:43Z",
          "databaseId": 50565430,
          "deleteBranchOnMerge": true,
          "description": "Fast, disk space efficient package manager",
          "descriptionHTML": "<div>Fast, disk space efficient package manager</div>",
          "diskUsage": 95244,
          "forkCount": 333,
          "forkingAllowed": true,
          "hasIssuesEnabled": true,
          "hasProjectsEnabled": false,
          "hasWikiEnabled": false,
          "homepageUrl": "https://pnpm.io",
          "id": "MDEwOlJlcG9zaXRvcnk1MDU2NTQzMA==",
          "isArchived": false,
          "isBlankIssuesEnabled": false,
          "isDisabled": false,
          "isEmpty": false,
          "isFork": false,
          "isInOrganization": true,
          "isLocked": false,
          "isMirror": false,
          "isPrivate": false,
          "isSecurityPolicyEnabled": true,
          "isTemplate": false,
          "isUserConfigurationRepository": false,
          "lockReason": null,
          "mergeCommitAllowed": false,
          "mirrorUrl": null,
          "name": "pnpm",
          "nameWithOwner": "pnpm/pnpm",
          "openGraphImageUrl": "https://repository-images.githubusercontent.com/50565430/8937cd00-7c0f-11e9-8fc4-8ef4a17af653",
          "projectsResourcePath": "/pnpm/pnpm/projects",
          "projectsUrl": "https://github.com/pnpm/pnpm/projects",
          "pushedAt": "2021-09-20T15:41:49Z",
          "rebaseMergeAllowed": true,
          "resourcePath": "/pnpm/pnpm",
          "securityPolicyUrl": "https://github.com/pnpm/pnpm/security/policy",
          "squashMergeAllowed": true,
          "sshUrl": "git@github.com:pnpm/pnpm.git",
          "stargazerCount": 12587,
          "tempCloneToken": "",
          "updatedAt": "2021-09-20T17:03:43Z",
          "url": "https://github.com/pnpm/pnpm",
          "usesCustomOpenGraphImage": true,
          "viewerCanAdminister": false,
          "viewerCanCreateProjects": true,
          "viewerCanSubscribe": true,
          "viewerCanUpdateTopics": false,
          "viewerDefaultCommitEmail": "pablosaez1995@gmail.com",
          "viewerDefaultMergeMethod": "SQUASH",
          "viewerHasStarred": true,
          "viewerPermission": "WRITE",
          "viewerPossibleCommitEmails": Array [
            "pablo.saez@hotmail.com",
            "pablo.saez01@alumnos.uach.cl",
            "pablosaez1995@gmail.com",
          ],
          "viewerSubscription": null,
          "visibility": "PUBLIC",
        },
        Object {
          "__typename": "Repository",
          "autoMergeAllowed": false,
          "createdAt": "2016-12-05T19:15:11Z",
          "databaseId": 75657790,
          "deleteBranchOnMerge": false,
          "description": "A tool for generating code based on a GraphQL schema and GraphQL operations (query/mutation/subscription), with flexible support for custom plugins. ",
          "descriptionHTML": "<div>A tool for generating code based on a GraphQL schema and GraphQL operations (query/mutation/subscription), with flexible support for custom plugins. </div>",
          "diskUsage": 72940,
          "forkCount": 819,
          "forkingAllowed": true,
          "hasIssuesEnabled": true,
          "hasProjectsEnabled": false,
          "hasWikiEnabled": false,
          "homepageUrl": "https://graphql-code-generator.com",
          "id": "MDEwOlJlcG9zaXRvcnk3NTY1Nzc5MA==",
          "isArchived": false,
          "isBlankIssuesEnabled": false,
          "isDisabled": false,
          "isEmpty": false,
          "isFork": false,
          "isInOrganization": false,
          "isLocked": false,
          "isMirror": false,
          "isPrivate": false,
          "isSecurityPolicyEnabled": false,
          "isTemplate": false,
          "isUserConfigurationRepository": false,
          "lockReason": null,
          "mergeCommitAllowed": false,
          "mirrorUrl": null,
          "name": "graphql-code-generator",
          "nameWithOwner": "dotansimha/graphql-code-generator",
          "openGraphImageUrl": "https://repository-images.githubusercontent.com/75657790/08db0980-c050-11e9-9924-d343fd5a3ddd",
          "projectsResourcePath": "/dotansimha/graphql-code-generator/projects",
          "projectsUrl": "https://github.com/dotansimha/graphql-code-generator/projects",
          "pushedAt": "2021-09-20T22:16:48Z",
          "rebaseMergeAllowed": false,
          "resourcePath": "/dotansimha/graphql-code-generator",
          "securityPolicyUrl": null,
          "squashMergeAllowed": true,
          "sshUrl": "git@github.com:dotansimha/graphql-code-generator.git",
          "stargazerCount": 7558,
          "tempCloneToken": "",
          "updatedAt": "2021-09-20T23:05:45Z",
          "url": "https://github.com/dotansimha/graphql-code-generator",
          "usesCustomOpenGraphImage": true,
          "viewerCanAdminister": false,
          "viewerCanCreateProjects": false,
          "viewerCanSubscribe": true,
          "viewerCanUpdateTopics": false,
          "viewerDefaultCommitEmail": "pablosaez1995@gmail.com",
          "viewerDefaultMergeMethod": "SQUASH",
          "viewerHasStarred": true,
          "viewerPermission": "READ",
          "viewerPossibleCommitEmails": Array [
            "pablo.saez@hotmail.com",
            "pablo.saez01@alumnos.uach.cl",
            "pablosaez1995@gmail.com",
          ],
          "viewerSubscription": "UNSUBSCRIBED",
          "visibility": "PUBLIC",
        },
        Object {
          "__typename": "Repository",
          "autoMergeAllowed": true,
          "createdAt": "2019-01-16T13:32:14Z",
          "databaseId": 166045424,
          "deleteBranchOnMerge": true,
          "description": "🚀 Fast and simple Node.js version manager, built in Rust",
          "descriptionHTML": "<div>
    <g-emoji class=\\"g-emoji\\" alias=\\"rocket\\" fallback-src=\\"https://github.githubassets.com/images/icons/emoji/unicode/1f680.png\\">🚀</g-emoji> Fast and simple Node.js version manager, built in Rust</div>",
          "diskUsage": 3346,
          "forkCount": 150,
          "forkingAllowed": true,
          "hasIssuesEnabled": true,
          "hasProjectsEnabled": true,
          "hasWikiEnabled": true,
          "homepageUrl": "https://fnm.vercel.app",
          "id": "MDEwOlJlcG9zaXRvcnkxNjYwNDU0MjQ=",
          "isArchived": false,
          "isBlankIssuesEnabled": true,
          "isDisabled": false,
          "isEmpty": false,
          "isFork": false,
          "isInOrganization": false,
          "isLocked": false,
          "isMirror": false,
          "isPrivate": false,
          "isSecurityPolicyEnabled": false,
          "isTemplate": false,
          "isUserConfigurationRepository": false,
          "lockReason": null,
          "mergeCommitAllowed": false,
          "mirrorUrl": null,
          "name": "fnm",
          "nameWithOwner": "Schniz/fnm",
          "openGraphImageUrl": "https://repository-images.githubusercontent.com/166045424/8289ae80-d301-11e9-9417-c43aeaee86a2",
          "projectsResourcePath": "/Schniz/fnm/projects",
          "projectsUrl": "https://github.com/Schniz/fnm/projects",
          "pushedAt": "2021-09-18T08:45:50Z",
          "rebaseMergeAllowed": false,
          "resourcePath": "/Schniz/fnm",
          "securityPolicyUrl": null,
          "squashMergeAllowed": true,
          "sshUrl": "git@github.com:Schniz/fnm.git",
          "stargazerCount": 4969,
          "tempCloneToken": "",
          "updatedAt": "2021-09-20T17:47:34Z",
          "url": "https://github.com/Schniz/fnm",
          "usesCustomOpenGraphImage": true,
          "viewerCanAdminister": false,
          "viewerCanCreateProjects": false,
          "viewerCanSubscribe": true,
          "viewerCanUpdateTopics": false,
          "viewerDefaultCommitEmail": "pablosaez1995@gmail.com",
          "viewerDefaultMergeMethod": "SQUASH",
          "viewerHasStarred": true,
          "viewerPermission": "READ",
          "viewerPossibleCommitEmails": Array [
            "pablo.saez@hotmail.com",
            "pablo.saez01@alumnos.uach.cl",
            "pablosaez1995@gmail.com",
          ],
          "viewerSubscription": "UNSUBSCRIBED",
          "visibility": "PUBLIC",
        },
        Object {
          "__typename": "Repository",
          "autoMergeAllowed": true,
          "createdAt": "2016-03-22T00:14:38Z",
          "databaseId": 54432168,
          "deleteBranchOnMerge": true,
          "description": ":wrench: Build, mock, and stitch a GraphQL schema using the schema language",
          "descriptionHTML": "<div>
    <g-emoji class=\\"g-emoji\\" alias=\\"wrench\\" fallback-src=\\"https://github.githubassets.com/images/icons/emoji/unicode/1f527.png\\">🔧</g-emoji> Build, mock, and stitch a GraphQL schema using the schema language</div>",
          "diskUsage": 60338,
          "forkCount": 674,
          "forkingAllowed": true,
          "hasIssuesEnabled": true,
          "hasProjectsEnabled": false,
          "hasWikiEnabled": false,
          "homepageUrl": "https://www.graphql-tools.com",
          "id": "MDEwOlJlcG9zaXRvcnk1NDQzMjE2OA==",
          "isArchived": false,
          "isBlankIssuesEnabled": false,
          "isDisabled": false,
          "isEmpty": false,
          "isFork": false,
          "isInOrganization": false,
          "isLocked": false,
          "isMirror": false,
          "isPrivate": false,
          "isSecurityPolicyEnabled": true,
          "isTemplate": false,
          "isUserConfigurationRepository": false,
          "lockReason": null,
          "mergeCommitAllowed": false,
          "mirrorUrl": null,
          "name": "graphql-tools",
          "nameWithOwner": "ardatan/graphql-tools",
          "openGraphImageUrl": "https://repository-images.githubusercontent.com/54432168/9081e980-76c5-11eb-9cdb-3f884f4fb498",
          "projectsResourcePath": "/ardatan/graphql-tools/projects",
          "projectsUrl": "https://github.com/ardatan/graphql-tools/projects",
          "pushedAt": "2021-09-20T22:39:00Z",
          "rebaseMergeAllowed": false,
          "resourcePath": "/ardatan/graphql-tools",
          "securityPolicyUrl": "https://github.com/ardatan/graphql-tools/security/policy",
          "squashMergeAllowed": true,
          "sshUrl": "git@github.com:ardatan/graphql-tools.git",
          "stargazerCount": 4358,
          "tempCloneToken": "",
          "updatedAt": "2021-09-20T22:36:50Z",
          "url": "https://github.com/ardatan/graphql-tools",
          "usesCustomOpenGraphImage": true,
          "viewerCanAdminister": false,
          "viewerCanCreateProjects": true,
          "viewerCanSubscribe": true,
          "viewerCanUpdateTopics": false,
          "viewerDefaultCommitEmail": "pablosaez1995@gmail.com",
          "viewerDefaultMergeMethod": "SQUASH",
          "viewerHasStarred": true,
          "viewerPermission": "WRITE",
          "viewerPossibleCommitEmails": Array [
            "pablo.saez@hotmail.com",
            "pablo.saez01@alumnos.uach.cl",
            "pablosaez1995@gmail.com",
          ],
          "viewerSubscription": "UNSUBSCRIBED",
          "visibility": "PUBLIC",
        },
        Object {
          "__typename": "Repository",
          "autoMergeAllowed": false,
          "createdAt": "2017-01-09T17:27:14Z",
          "databaseId": 78452015,
          "deleteBranchOnMerge": true,
          "description": "LoopBack makes it easy to build modern API applications that require complex integrations.",
          "descriptionHTML": "<div>LoopBack makes it easy to build modern API applications that require complex integrations.</div>",
          "diskUsage": 141235,
          "forkCount": 836,
          "forkingAllowed": true,
          "hasIssuesEnabled": true,
          "hasProjectsEnabled": false,
          "hasWikiEnabled": true,
          "homepageUrl": "https://loopback.io",
          "id": "MDEwOlJlcG9zaXRvcnk3ODQ1MjAxNQ==",
          "isArchived": false,
          "isBlankIssuesEnabled": false,
          "isDisabled": false,
          "isEmpty": false,
          "isFork": false,
          "isInOrganization": true,
          "isLocked": false,
          "isMirror": false,
          "isPrivate": false,
          "isSecurityPolicyEnabled": true,
          "isTemplate": false,
          "isUserConfigurationRepository": false,
          "lockReason": null,
          "mergeCommitAllowed": false,
          "mirrorUrl": null,
          "name": "loopback-next",
          "nameWithOwner": "loopbackio/loopback-next",
          "openGraphImageUrl": "https://repository-images.githubusercontent.com/78452015/2e9bdb80-6b51-11e9-9630-fdcead4ff24d",
          "projectsResourcePath": "/loopbackio/loopback-next/projects",
          "projectsUrl": "https://github.com/loopbackio/loopback-next/projects",
          "pushedAt": "2021-09-20T22:19:26Z",
          "rebaseMergeAllowed": true,
          "resourcePath": "/loopbackio/loopback-next",
          "securityPolicyUrl": "https://github.com/loopbackio/loopback-next/security/policy",
          "squashMergeAllowed": false,
          "sshUrl": "git@github.com:loopbackio/loopback-next.git",
          "stargazerCount": 3838,
          "tempCloneToken": "",
          "updatedAt": "2021-09-20T19:39:29Z",
          "url": "https://github.com/loopbackio/loopback-next",
          "usesCustomOpenGraphImage": true,
          "viewerCanAdminister": false,
          "viewerCanCreateProjects": false,
          "viewerCanSubscribe": true,
          "viewerCanUpdateTopics": false,
          "viewerDefaultCommitEmail": "pablosaez1995@gmail.com",
          "viewerDefaultMergeMethod": "REBASE",
          "viewerHasStarred": false,
          "viewerPermission": "READ",
          "viewerPossibleCommitEmails": Array [
            "pablo.saez@hotmail.com",
            "pablo.saez01@alumnos.uach.cl",
            "pablosaez1995@gmail.com",
          ],
          "viewerSubscription": "UNSUBSCRIBED",
          "visibility": "PUBLIC",
        },
        Object {
          "__typename": "Repository",
          "autoMergeAllowed": true,
          "createdAt": "2017-03-25T21:08:30Z",
          "databaseId": 86188653,
          "deleteBranchOnMerge": true,
          "description": "✨⚡️ A beautiful feature-rich GraphQL Client for all platforms.",
          "descriptionHTML": "<div>
    <g-emoji class=\\"g-emoji\\" alias=\\"sparkles\\" fallback-src=\\"https://github.githubassets.com/images/icons/emoji/unicode/2728.png\\">✨</g-emoji><g-emoji class=\\"g-emoji\\" alias=\\"zap\\" fallback-src=\\"https://github.githubassets.com/images/icons/emoji/unicode/26a1.png\\">⚡️</g-emoji> A beautiful feature-rich GraphQL Client for all platforms.</div>",
          "diskUsage": 32881,
          "forkCount": 153,
          "forkingAllowed": true,
          "hasIssuesEnabled": true,
          "hasProjectsEnabled": true,
          "hasWikiEnabled": true,
          "homepageUrl": "https://altair.sirmuel.design/",
          "id": "MDEwOlJlcG9zaXRvcnk4NjE4ODY1Mw==",
          "isArchived": false,
          "isBlankIssuesEnabled": true,
          "isDisabled": false,
          "isEmpty": false,
          "isFork": false,
          "isInOrganization": true,
          "isLocked": false,
          "isMirror": false,
          "isPrivate": false,
          "isSecurityPolicyEnabled": true,
          "isTemplate": false,
          "isUserConfigurationRepository": false,
          "lockReason": null,
          "mergeCommitAllowed": true,
          "mirrorUrl": null,
          "name": "altair",
          "nameWithOwner": "altair-graphql/altair",
          "openGraphImageUrl": "https://repository-images.githubusercontent.com/86188653/dca14d00-9d6f-11e9-9542-f3b7ae7f4bc7",
          "projectsResourcePath": "/altair-graphql/altair/projects",
          "projectsUrl": "https://github.com/altair-graphql/altair/projects",
          "pushedAt": "2021-09-20T22:55:19Z",
          "rebaseMergeAllowed": true,
          "resourcePath": "/altair-graphql/altair",
          "securityPolicyUrl": "https://github.com/altair-graphql/altair/security/policy",
          "squashMergeAllowed": true,
          "sshUrl": "git@github.com:altair-graphql/altair.git",
          "stargazerCount": 3642,
          "tempCloneToken": "",
          "updatedAt": "2021-09-20T22:53:50Z",
          "url": "https://github.com/altair-graphql/altair",
          "usesCustomOpenGraphImage": true,
          "viewerCanAdminister": false,
          "viewerCanCreateProjects": false,
          "viewerCanSubscribe": true,
          "viewerCanUpdateTopics": false,
          "viewerDefaultCommitEmail": "pablosaez1995@gmail.com",
          "viewerDefaultMergeMethod": "MERGE",
          "viewerHasStarred": true,
          "viewerPermission": "READ",
          "viewerPossibleCommitEmails": Array [
            "pablo.saez@hotmail.com",
            "pablo.saez01@alumnos.uach.cl",
            "pablosaez1995@gmail.com",
          ],
          "viewerSubscription": null,
          "visibility": "PUBLIC",
        },
      ],
      "pageInfo": Object {
        "__typename": "PageInfo",
        "endCursor": "Y3Vyc29yOnYyOpLNDjrOBSMibQ==",
        "hasNextPage": true,
        "hasPreviousPage": false,
        "startCursor": "Y3Vyc29yOnYyOpLOAAEin84BP1oB",
      },
    }
  `);
});
